### ISSUE TITLE
Still in beta?

### ISSUE THREAD

**Issue by cveld** [ajuhos/sharpnr.js#1]
Hi Adam,

I am very impressed by your async/await implementation! I wonder if this sharpnr.js is still your recommended codebase to incorporate into my solutions? As it is already 3 years old, maybe there are better solutions to go for. E.g. a TypeScript based solution, or another JavaScript framework or compiler out there.
Can you advise?

Regards, Carl

**Comment by ajuhos** [comment]
Hi Carl,

Sharpnr.js is now obsolete and deprecreated, that's why it is abandoned.

In our current projects we use our custom JavaScript superset called InqScript. Which adds async/await support and several other features to JavaScript via our modular compiler. It is available on GitHub and NPM. The system have been separated into several NPM modules, but the [compiler module](https://github.com/WeAreBreak/inqc) and the [Language Specification](https://github.com/WeAreBreak/cellscript/blob/master/docs/CellScript%20Language%20Specification.pdf) should be a great start.

Also you can try [BabelJS](https://babeljs.io/) or other compilers.

**Comment by cveld** [comment]
I am reading the following:
http://pouchdb.com/2015/03/05/taming-the-async-beast-with-es7.html

The babeljs/regenerator stack adds 60kB to the wire. What is the story with inqscript? 

-----Oorspronkelijk bericht-----
Van: "Adam Juhos" notifications@github.com
Verzonden: ‎11-‎9-‎2015 15:48
Aan: "ajuhos/sharpnr.js" sharpnr.js@noreply.github.com
CC: "cveld" carl@intveld.nl
Onderwerp: Re: [sharpnr.js] Still in beta? (#1)

Hi Carl,
Sharpnr.js is now obsolete and deprecreated, that's why it is abandoned.
In our current projects we use our custom JavaScript superset called InqScript. Which adds async/await support and several other features to JavaScript via our modular compiler. It is available on GitHub and NPM. The system have been separated into several NPM modules, but the compiler module and the Language Specification should be a great start.
Also you can try BabelJS or other compilers.

**Comment by cveld** [comment]
Wow impressive!
Are you planning to contribute to TypeScript? As I really love the static
typing that TypeScript is offering, I don't want to loose that. But I am
also desperate to start using the async/await pattern!

I have just checked BabelJS and now I am wondering if there is a standard
setup within Visual Studio that combines TypeScript and BabelJS somehow?

2015-09-11 15:46 GMT+02:00 Adam Juhos notifications@github.com:
